permalink: pretty

plugins:
  - jekyll-remote-theme

remote_theme: dhilanr/jekyll-theme-crestlex

url: https://www.tcoptrob.org
baseurl: /OptRob-25

title: 2025 Optimization for Robotics Summer School

alert:
    - success