permalink: pretty

plugins:
  - jekyll-remote-theme

remote_theme: dhilanr/jekyll-theme-crestlex

url: https://www.tcoptrob.org
baseurl: /summer-school-2025

title: 2025 Optimization for Robotics Summer School

# alert:
#     - success