# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: CI Website Summer School 2025

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    if: github.event_name != 'workflow_dispatch'
    name: OS:${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
    env:
      CI_HOME: ${{github.workspace}}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Install Ubuntu packages
        run: sudo apt-get install -y ruby-full build-essential zlib1g-dev
      - name: Install Jekyll
        run: |
          echo 'gem: --user-install' >> ~/.gemrc
          GEM_VERSION=$(gem -v)
          export PATH=$HOME/.local/share/gem/ruby/$GEM_VERSION/bin:$PATH
          echo $PATH
          gem install jekyll bundler
      - name: Install deps and build website
        run: |
          GEM_VERSION=$(gem -v)
          export PATH=$HOME/.local/share/gem/ruby/$GEM_VERSION/bin:$PATH
          echo $PATH
          git config user.name github-actions
          git config user.email github-actions@github.com
          cd ${{github.workspace}}
          bundle install
          bundle exec jekyll build
          git checkout docs
          mv _site/* .
          rm -r _site
          git add .
          git commit -am "Update website"
          git push
